image:
  registry: docker.io
  repository: woojoong/namespace-watcher-informer
  # tag: 0.0.1
  pullPolicy: Always
  pullSecrets: []

nameOverride: ""
fullnameOverride: ""

metadata:
  deploymentAnnotations: []
  deploymentLabels: []

replicaCount: 1

serviceAccount:
  name: namespace-watcher-informer-sa

security:
  podSecurityContext: {}
  securityContext: {}

nodeSelector:
  deployment: {}

configs:
  excludedNamespaces:
    - kube-system
    - kube-public
    - kube-node-lease