apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "namespace-watcher-controller.fullname" . }}
  {{- with .Values.metadata.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "namespace-watcher-controller.labels" . | nindent 4 }}
    {{- with .Values.metadata.deploymentLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "namespace-watcher-controller.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "namespace-watcher-controller.labels" . | nindent 8 }}
        version: {{ .Chart.AppVersion }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.security.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector.deployment }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: controller
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: EXCLUDED_NAMESPACES
              value: {{ include "namespace-watcher-controller.excludedNamespaces" . }}
          command:
            - /manager
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
          {{- with .Values.security.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10